spring.application.name=ms-clientes
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/clientes
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

jwt.secret=clave_super_secreta_12345678901234567890