spring.application.name=ms-automotriz
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/automotriz
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
